### ISSUE TITLE
A Show class specialised for Text

### ISSUE THREAD

**Issue by nikita-volkov** [bos/text#106]
The pattern `(Text.pack . show)` is too ubiquitous for there not to exist a specialised and better performing version of the `Show` class for `Text`.

I want to propose a class which provides a universal interface to all three primary types of this library: builder and strict and lazy texts. 

It could be implemented as follows:

```haskell
import qualified Data.Text as S
import qualified Data.Text.Lazy as L
import qualified Data.Text.Lazy.Builder as B
import qualified Data.Text.Lazy.Builder.Int as BI
import qualified Data.Text.Lazy.Builder.RealFloat as BRF

class Show a where
  builder :: a -> B.Builder
  builder = B.fromLazyText . lazyText
  strictText :: a -> S.Text
  strictText = L.toStrict . lazyText
  lazyText :: a -> L.Text
  lazyText = B.toLazyText . builder

instance Show Int where
  builder = BI.decimal

instance Show Float where
  builder = BRF.realFloat

```

**Comment by bos** [comment]
http://hackage.haskell.org/package/text-show
