### ISSUE TITLE
cycle function for lazy Texts

### ISSUE THREAD

**Issue by RyanGlScott** [bos/text#110]
I would find it useful to have a `cycle` function for lazy `Text`s, similar to the ones for [lists](http://hackage.haskell.org/package/base-4.7.0.2/docs/Prelude.html#v:cycle) and [lazy `ByteString`s](http://hackage.haskell.org/package/bytestring-0.10.4.1/docs/Data-ByteString-Lazy.html#v:cycle).

**Comment by bos** [comment]
Pull request welcome :-)

**Comment by RyanGlScott** [comment]
Thanks! This was fixed in 62e0bb7b0912572cb1fb4e760a6143dffe99dc56.
