### ISSUE TITLE
strictEncode/OnEncodeError seem to be unused

### ISSUE THREAD

**Issue by mightybyte** [bos/text#112]
Is there a reason OnEncodeError and strictEncode are there?  I just noticed them today and it threw me for a loop because it made me think that there is a way encoding can fail.  On further inspection it appears that they are not used at all.  If you're not removing them because of backwards compatibility, then it would be nice if the comments mentioned that they are unused.  Or even better yet, deprecated them.

**Comment by bos** [comment]
Thanks for noticing these.
