### ISSUE TITLE
Run-time errors in the Data.Data instance

### ISSUE THREAD

**Issue by co-dan** [bos/text#113]
The current implementation of the Data.Data typeclass for lazy Text throws run-time errors: https://github.com/bos/text/blob/master/Data/Text/Lazy.hs#L358

Is there a way to fix this somehow?

**Comment by bos** [comment]
This is expected behaviour. The `toConstr` function is expected to return a constructor, but `Text` is deliberately opaque.

**Comment by co-dan** [comment]
Then maybe `Text` should not implement the Data instance? My code is throwing run-time errors because of this
