### ISSUE TITLE
Provide Binary instances for `Text`

### ISSUE THREAD

**Issue by hvr** [bos/text#115]
Right now one has to resort to unofficial orphan sources such as https://hackage.haskell.org/package/text-binary

Even  `String` and `ByteString` have `Binary` instances

Is there a reason `text` doesn't provide `Binary` instances for `Text`?

**Comment by andrewthad** [comment]
I think that [this answer](http://stackoverflow.com/a/19365928/1405768) sort of addresses the rationale. However, I disagree with it because not having the instance destroys the utility of GHC's Generics for getting free `Binary` instances of things that have text in them.

**Comment by hvr** [comment]
Well, that answer somewhat implies imho that the `Binary` instance for `String` is ill-advised too...

Personally I see no problem either for `Text` to simply define a canonical instance for `Binary Text`, as `Binary` doesn't claim (afaik) to implement any published standard binary serialisation format. Personally I don't care whether much whether `Binary Text` encodes as UTF8, UTF16(LE|BE), UTF32 or something totally else as long as it's reasonably optimised (although I'd think that UTF8 would represent a good tradeoff in terms of space and time for "western" text-content)

If somebody needed a specific encoding, `newtype`-wrappers around `Text` are your friend...

Otoh, I'd like to know what @dcoutts thinks about this (given he's involved in http://code.haskell.org/~duncan/binary-experiment/binary.pdf)

**Comment by dcoutts** [comment]
In the original binary package it was a bit unclear to users whether the Binary class was for the purpose of conveniently making particular binary formats, or whether it was for serialising Haskell types to and from some impl-defined binary rep. The authors of the binary package intend for it to be the latter, and as such the instance for `Text` can be chosen based on size and performance goals, and not based on users trying to meet some externally defined format. For that they need to use other functions, not the Binary class. We hope to make this "binary formats" vs "Haskell value serialisation" distinction clearer in future versions of the binary package (when we introduce a new format and class for the Haskell value serialisation side of things).

**Comment by bos** [comment]
I'm not going to add a dependency on binary to text, because binary doesn't ship with ghc or the Haskell Platform. The right place for an instance is in binary.

**Comment by hvr** [comment]
> because binary doesn't ship with ghc or the Haskell Platform.

?! :-)

https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/VersionHistory

**Comment by hvr** [comment]
@bos *bump*

**Comment by bos** [comment]
Oops, thanks for the correction.

**Comment by hvr** [comment]
:beers:
