### ISSUE TITLE
Exponential build times with nested toCaseFold

### ISSUE THREAD

**Issue by larskuhtz** [bos/text#116]
I observed very long build times for modules that make use of `toCaseFold` when `-O` is enabled. In particular when calls to `toCaseFold` are nested build times can grow exponentially.

Here are some benchmark results that illustrate the problem: https://github.com/larskuhtz/toCaseFoldBuildTimes.

I think that the issue is related to the inlining of `foldMapping` here https://github.com/bos/text/blob/master/Data/Text/Internal/Fusion/CaseMapping.hs#L325.

**Comment by bos** [comment]
I've got a fix written for this. Bear with me as I ensure that it's correct and fast enough.

**Comment by bos** [comment]
Fixed in HEAD.

**Comment by larskuhtz** [comment]
Thanks.
