### ISSUE TITLE
Maintenance release of 1.1.x with GHC<7.4, bytestring>=0.10 support?

### ISSUE THREAD

**Issue by bergmark** [bos/text#120]
Related: https://github.com/bos/text/issues/108

We are running builds against multiple ghcs and versions for curation. The fact that `text-1.1.*`  doesn't build with `bytestring >= 0.10` is causing us problems, e.g. http://matrix.hackage.haskell.org/package/process-listlike#GHC-7.2/process-listlike-1.0

Would it be possible to get a `1.1.1.4` release that fixes this?

I prepared and tested a commit for this (can't send PR's against tags): https://github.com/bergmark/text/commit/fba4081026ae7d70e26c10e28ce44f2becce4d88

Thanks,
Adam

**Comment by bos** [comment]
I tried to upload a new 1.1 for you, but I'm blocked by a [regression in Hackage](https://github.com/haskell/cabal/issues/2586).

**Comment by bergmark** [comment]
Thanks for trying! A lot of packages are affected by this so hopefully there will be a fix soon...

**Comment by bos** [comment]
1.1.1.4 is out now.

**Comment by bergmark** [comment]
Thank you Bryan, green bars everywhere!
