### ISSUE TITLE
The Data.Text.Internal.text function is not strict enough

### ISSUE THREAD

**Issue by tibbe** [bos/text#139]
I don't know if this has any practical implications (i.e. I haven't measured) but the [Data.Text.Internal.text](https://github.com/bos/text/blob/93e3705127dc9a01c5216d7462877a27d29f8f01/Data/Text/Internal.hs#L92) function isn't strict in its first and second (`Int`) arguments. This might lead to extra unboxing.

The reason it's not strict is that if the guard condition is true, the these two arguments aren't used.

**Comment by bos** [comment]
I took a look at the generated Core, and couldn't see a difference with strictness annotations.
