### ISSUE TITLE
no safe head/tail functions

### ISSUE THREAD

**Issue by alexanderkjeldaas** [bos/text#149]
I couldn't see this reported elsewhere, but to my surprise I can't find the functions
`headMay, tailMay :: Text -> Maybe Char` in the basic interface.

**Comment by mchaver** [comment]
I made safe versions here, but I can't seem to run the package in `cabal repl` or run cabal tests, so I haven't setup tests yet.
https://github.com/mchaver/text/commit/ead92a7890dc00688f235eb55de41ee1130c9990

**Comment by bos** [comment]
`uncons`
