### ISSUE TITLE
Lazy text does not have O(1) last function

### ISSUE THREAD

**Issue by andrewthad** [bos/text#150]
The `Data.Text.Lazy` docs for `last` say that it runs in `O(1)`. It actually runs in `O(n/c)` (just like for lazy bytestrings) where `n` is the size of the lazy bytestring and `c` is the average chunk size.

**Comment by bos** [comment]
Thanks for pointing out this mistake. Could you please submit a pull request to fix it?

**Comment by andrewthad** [comment]
https://github.com/bos/text/pull/162

**Comment by kRITZCREEK** [comment]
This seems like it could be close, the fix has been merged.
