### ISSUE TITLE
Un-orphan the Text instances

### ISSUE THREAD

**Issue by ezyang** [bos/text#170]
At the moment, Text's instances live in Data.Text, whereas the implementation of the Text type is in Data.Text.Internals. This means that all of these instances are orphaned. That's not great. Would be better to avoid orphanhood. Among other difficulties, orphan instances means that Haddock is unable to report instances for the type; see https://www.stackage.org/haddock/lts-7.12/text-1.2.2.1/Data-Text.html#t:Text for an example.

**Comment by RyanGlScott** [comment]
See also #60.

**Comment by ezyang** [comment]
Closing as dupe.
