### ISSUE TITLE
Push a release?

### ISSUE THREAD

**Issue by bgamari** [bos/text#172]
There have been a number of fixes merged since the last release. It seems like it's time for another. Currently GHC drowns me with fragile RULE warnings with every build.

**Comment by metaleap** [comment]
`snd`ed!

**Comment by RyanGlScott** [comment]
It looks like your wish has been granted with the release of [`text-1.2.2.2`](http://hackage.haskell.org/package/text-1.2.2.2).

**Comment by bos** [comment]
If it were done when 'tis done, then 'twere well
It were done quickly: if the assassination
Could trammel up the consequence, and catch
With his surcease success; that but this blow
Might be the be-all and the end-all here,
But here, upon this bank and shoal of time,
We'ld jump the life to come.
