### ISSUE TITLE
Unbuffered handles write Text character-wise

### ISSUE THREAD

**Issue by quchen** [bos/text#179]
[`Data.Text.IO.hPutStr`](https://github.com/bos/text/blob/bb3d8623d83b327f99d0520237e5ab44dbb5a9d8/Data/Text/IO.hs#L171) writes data to the buffer character-wise when it is unbuffered, which results in a `write()` syscall for each character, making the Text version as unperformant as the `String` one. Text should write all characters, or at least a decently sized chunk of characters, to the handle instead, instead of worrying about how to handle the buffer itself.

To show the issue, compile and run
```haskell
{-# LANGUAGE OverloadedStrings #-}

import qualified Data.Text.IO as T
import           System.IO

main :: IO ()
main = do
    -- STDOUT is unbuffered by default
    hPutStrLn stdout "hello world"
    T.hPutStrLn stdout "hello world"
```
with
```bash
stack ghc Test.hs --resolver lts-8 --package text && strace ./Test
```

**Comment by bos** [comment]
It's not obvious to me how to fix this, because there's a vast amount of complexity in the way around encoding and so on. If you find a way to fix this relatively straightforwardly then please submit a PR, but I don't intend to fix this myself (or keep this issue open) I'm afraid.
