### ISSUE TITLE
Data.Text.Lazy.takeWhileEnd is broken

### ISSUE THREAD

**Issue by bucklereed** [bos/text#184]
With text-1.2.2.2:

```
*Main> import qualified Data.Text as T
*Main T> T.takeWhileEnd isSpace $ "foobar"
""
*Main T> T.null . T.takeWhileEnd isSpace $ "foobar"
True
*Main T> import qualified Data.Text.Lazy as LT
*Main T LT> LT.takeWhileEnd isSpace $ "foobar"
""
*Main T LT> LT.null . LT.takeWhileEnd isSpace $ "foobar"
False
*Main T LT> LT.length . LT.takeWhileEnd isSpace $ "foobar"
0
```

As can be seen, strict Text gives the expected results; lazy Text constructs a very weird thing that has zero length, looks empty, but is not null. The bug is possibly in Data.Text.Lazy.null rather than takeWhileEnd?

**Comment by Gabriel439** [comment]
Actually, it's `Data.Text.null` that is broken.  It's currently implemented as:

```haskell
-- | /O(1)/ Tests whether a 'Text' is empty or not.  Subject to
-- fusion.
null :: Text -> Bool
null Empty = True
null _     = False
{-# INLINE [1] null #-}
```

... which is wrong since it will not correctly detect that something like `Chunk "" Empty` is null.  It really should be implemented as something like:

```haskell
null = foldrChunks (\text rest -> Data.Text.null text && rest) True
```

This is a pretty serious bug

**Comment by bos** [comment]
It's actually the implementation of lazy `takeWhileEnd` that is wrong, because it violates the invariant that every `Chunk` must be non-empty.

**Comment by bos** [comment]
[Fixed here](https://github.com/bos/text/commit/054d273a29be6c7f35028eb0d67f38ea7979de73#diff-460849403c15c51bf41383aca95ccaacL1153). Thanks for the report!

**Comment by bos** [comment]
cc @PaulCapron :-)
